### ISSUE TITLE
R Jupyter

### ISSUE THREAD

**Issue by LeiliPR** [jdebacker/CompEcon_Fall19#20]
The link shows how to install the R kernel for Jupyter notebooks via the Anaconda Navigator.
[here](https://docs.anaconda.com/anaconda/navigator/tutorials/r-lang/)

**Comment by jdebacker** [comment]
The link that @LeiliPR shared shows how to install the R kernel for Jupyter notebooks via the Anaconda Navigator.

**Comment by jdebacker** [comment]
resolved with PR #21
